MOD_ACTIONS = {
    'acceptmoderatorinvite': 'User accepted invitation to moderate',
    'add_community_topics': 'Added community topic(s)',
    'addcontributor': 'Contributor added',
    'addmoderator': 'Moderator added',
    'approvecomment': 'Comment approved',
    'approvelink': 'Link post approved',
    'banuser': 'User banned',
    'collections': 'Did some collections-related stuff',
    'community_styling': 'Changed community style',
    'community_widgets': 'Changed community widgets',
    'create_scheduled_post': 'Created scheduled post',
    'createrule': 'Rule created',
    'delete_scheduled_post': 'Scheduled post deleted',
    'deleterule': 'Rule removed',
    'distinguish': 'Distinguished',
    'edit_post_requirements': 'Edited post requirements',
    'edit_scheduled_post': 'Scheduled post edited',
    'editflair': 'Flair edited',
    'editrule': 'Rule edited',
    'editsettings': 'Settings edited',
    'events': 'Did some events-related stuff',
    'hidden_award': 'Award hidden',
    'ignorereports': 'Reports ignored',
    'invitemoderator': 'Moderator invited',
    'lock': 'Locked',
    'marknsfw': 'Marked as NSFW',
    'markoriginalcontent': 'Marked as OC',
    'modmail_enrollment': 'Modmail enrollment',
    'muteuser': 'User muted from modmail',
    'remove_community_topics': 'Removed community topic(s)',
    'removecomment': 'Comment removed',
    'removecontributor': 'Contributor removed',
    'removelink': 'Link posted removed',
    'removemoderator': 'Moderator removed',
    'removewikicontributor': 'Wiki contributor removed',
    'reorderrules': 'Rules reordered',
    'setcontestmode': 'Contest mode set',
    'setpermissions': 'Permissions set',
    'setsuggestedsort': 'Set suggested sort',
    'showcomment': 'Comment shown',
    'spamcomment': 'Comment removed as spam',
    'spamlink': 'Link post removed as spam',
    'spoiler': 'Marked as spoiler',
    'sticky': 'Stickied',
    'submit_scheduled_post': 'Scheduled post submitted',
    'unbanuser': 'User unbanned',
    'unignorereports': 'Reports unignored',
    'uninvitemoderator': 'Moderator uninvited',
    'unlock': 'Unlocked',
    'unmuteuser': 'User unmuted from modmail',
    'unsetcontestmode': 'Contest mode unset',
    'unspoiler': 'Unmarked as spoiler',
    'unsticky': 'Unstickied',
    'wikibanned': 'Banned from wiki',
    'wikicontributor': 'Added as wiki contributor',
    'wikipagelisted': 'Wiki page listed',
    'wikipermlevel': 'Permission level of wiki changed',
    'wikirevise': 'Wiki revised',
    'wikiunbanned': 'Unbanned from wiki',
}

IMPORTANT_ACTIONS = [
    'approvecomment', 'approvelink', 'banuser', 'editflair', 'ignorereports', 'lock', 'marknsfw', 'markoriginalcontent',
    'muteuser', 'removecomment', 'removelink', 'showcomment', 'spamcomment', 'spamlink', 'spoiler', 'unbanuser',
    'unignorereports', 'unlock', 'unmuteuser', 'unspoiler', 'wikibanned', 'wikiunbanned'
]
