MOD_ACTIONS = {
    'acceptmoderatorinvite': 'User accepted invitation to moderate',
    'add_community_topics': 'Added community topic(s)',
    'addcontributor': 'Contributor added',
    'addmoderator': 'Moderator added',
    'approvecomment': 'Comment approved',
    'approvelink': 'Link post approved',
    'banuser': 'User banned',
    'collections': 'Did some collections-related stuff',
    'community_styling': 'Changed community style',
    'community_widgets': 'Changed community widgets',
    'create_scheduled_post': 'Created scheduled post',
    'createrule': 'Rule created',
    'delete_scheduled_post': 'Scheduled post deleted',
    'deleterule': 'Rule removed',
    'distinguish': 'Distinguished',
    'edit_post_requirements': 'Edited post requirements',
    'edit_scheduled_post': 'Scheduled post edited',
    'editflair': 'Flair edited',
    'editrule': 'Rule edited',
    'editsettings': 'Settings edited',
    'events': 'Did some events-related stuff',
    'hidden_award': 'Award hidden',
    'ignorereports': 'Reports ignored',
    'invitemoderator': 'Moderator invited',
    'lock': 'Locked',
    'marknsfw': 'Marked as NSFW',
    'markoriginalcontent': 'Marked as OC',
    'modmail_enrollment': 'Modmail enrollment',
    'muteuser': 'User muted from modmail',
    'remove_community_topics': 'Removed community topic(s)',
    'removecomment': 'Comment removed',
    'removecontributor': 'Contributor removed',
    'removelink': 'Link posted removed',
    'removemoderator': 'Moderator removed',
    'removewikicontributor': 'Wiki contributor removed',
    'reorderrules': 'Rules reordered',
    'setcontestmode': 'Contest mode set',
    'setpermissions': 'Permissions set',
    'setsuggestedsort': 'Set suggested sort',
    'showcomment': 'Comment shown',
    'spamcomment': 'Comment removed as spam',
    'spamlink': 'Link post removed as spam',
    'spoiler': 'Marked as spoiler',
    'sticky': 'Stickied',
    'submit_scheduled_post': 'Scheduled post submitted',
    'unbanuser': 'User unbanned',
    'unignorereports': 'Reports unignored',
    'uninvitemoderator': 'Moderator uninvited',
    'unlock': 'Unlocked',
    'unmuteuser': 'User unmuted from modmail',
    'unsetcontestmode': 'Contest mode unset',
    'unspoiler': 'Unmarked as spoiler',
    'unsticky': 'Unstickied',
    'wikibanned': 'Banned from wiki',
    'wikicontributor': 'Added as wiki contributor',
    'wikipagelisted': 'Wiki page listed',
    'wikipermlevel': 'Permission level of wiki changed',
    'wikirevise': 'Wiki revised',
    'wikiunbanned': 'Unbanned from wiki',
    'setcontestmode': 'Contest mode set',
    'unsetcontestmode': 'Contest mode unset',
    'createrule': 'Rule created',
    'editerule': 'Rule edited',
    'deleterule': 'Rule deleted',
    'create_scheduled_post': 'Scheduled post created',
    'edit_scheduled_post': 'Scheduled post edited',
    'delete_scheduled_post': 'Scheduled post deleted',
    'submit_scheduled_post': 'Scheduled post submitted',
    'addnote': 'User note added',
    'deletenote': 'User note deleted',
    'addremovalreason': 'Removal reason added',
    'createremovalreason': 'Removal reason created',
    'updateremovalreason': 'Removal reason updated',
    'deleteremovalreason': 'Removal reason deleted'
}

IMPORTANT_ACTIONS = [
    'approvecomment', 'approvelink', 'banuser', 'editflair', 'ignorereports', 'lock', 'marknsfw', 'markoriginalcontent',
    'muteuser', 'removecomment', 'removelink', 'showcomment', 'spamcomment', 'spamlink', 'spoiler', 'unbanuser',
    'unignorereports', 'unlock', 'unmuteuser', 'unspoiler', 'wikibanned', 'wikiunbanned'
]

MODACTION_WH = {
    'approvecomment': 'Comentario aprobado',
    'approvelink': 'Post aprobado',
    'banuser': 'Usuario baneado',
    'editflair': 'Flair editado',
    'ignorereports': 'Reportes ignorados',
    'lock': 'Post/comentario bloqueado',
    'marknsfw': 'Post marcado como NSFW',
    'markoriginalcontent': 'Post marcado como OC',
    'muteuser': 'Usuario muteado del modmail',
    'removecomment': 'Comentario retirado',
    'removelink': 'Post retirado',
    'showcomment': 'Comentario mostrado',
    'spamcomment': 'Comentario marcado como spam',
    'spamlink': 'Post marcado como spam',
    'spoiler': 'Post marcado como spoiler',
    'unbanuser': 'Usuario desbaneado',
    'unignorereports': 'Reportes restaurados',
    'unlock': 'Post/comentario desbloqueado',
    'unmuteuser': 'Usuario desmuteado del modmail',
    'unspoiler': 'Post desmarcado como spoiler',
    'sticky': 'Post/comentario fijado',
    'unsticky': 'Post/comentario desfijado',
    'setcontestmode': 'Modo concurso activado',
    'unsetcontestmode': 'Modo concurso desactivado',
    'createrule': 'Regla creada',
    'editerule': 'Regla editada',
    'deleterule': 'Regla eliminada',
    'create_scheduled_post': 'Post programado creado',
    'edit_scheduled_post': 'Post programado editado',
    'delete_scheduled_post': 'Post programado borrado',
    'submit_scheduled_post': 'Post programado enviado',
    'addnote': 'Nota de usuario agregada',
    'deletenote': 'Nota de usuario eliminada',
    'createremovalreason': 'Razón de eliminado creada',
    'updateremovalreason': 'Razón de eliminado actualizada',
    'deleteremovalreason': 'Razón de eliminado borrada',
}

USELESS_DETAILS = {
    'confirm_ham': '',
    'remove': '',
    'unspam': 'Estaba filtrado por el AutoMod'
}
